[package]
name = "asus/daynightcycleandevent"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
vide = "centau/vide@0.3.1"
Quid = "6531503070/quid@1.0.1"
sha256 = "dekkonot/sha256@1.0.1"
Signal = "sleitnick/signal@^1"
TableUtil = "sleitnick/table-util@^1"
Lyra = "paradoxum-games/lyra@0.6.0"
zoneplus = "mattschrubb/zoneplus@3.2.0"
cmdr = "evaera/cmdr@1.12.0"
t = "osyrisrblx/t@3.1.1"